package:
  name: shap
  version: 0.41.0
  top-level:
    - shap
source:
  url: https://files.pythonhosted.org/packages/ed/bb/b48bb3fe1b47e7673b037ed9627746eb1bf9f3ee5b45289f5ab6a26089ef/shap-0.41.0.tar.gz
  sha256: a49ea4d65aadbc845a695fa3d7ea0bdfc8c928b8e213b0feedf5868ade4b3ca5
  patches:
    - patches/notnumba.patch
about:
  home: http://github.com/slundberg/shap
  PyPI: https://pypi.org/project/shap
  summary: A unified approach to explain the output of any machine learning model.
  license: MIT